### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by cmdcolin** [tjs23/unknome#1]
Just thought i'd report it

There was a recent nature news article (https://www.nature.com/articles/d41586-024-01548-w) linking to it so figured it would be nice to explore if it was possible to still be online!

broken link for me: http://unknome.org redirects to https://unknome.mrc-lmb.cam.ac.uk/ which is broken. the http version of the latter is infinite load it seems

**Comment by cmdcolin** [comment]
random side note: the github contents of this repo seem to be unrelated to the unknome (??)

**Comment by cmdcolin** [comment]
might be https://github.com/tjs23/unknome_db

**Comment by tjs23** [comment]
Thanks for the report. The site was back up last week; it needed a prod after an SSL certificate update. 

Regarding repos "unknome" is for scripts that support the biological analyses in the original paper and "unknome_db" relates to the database that underpins the website. I'll make this clearer in the READMEs.
